-- Indexes for Thread Inventory System (excluding PK and unique constraints)
CREATE INDEX idx_batch_transactions_from_warehouse ON public.batch_transactions USING btree (from_warehouse_id);
CREATE INDEX idx_batch_transactions_lot_id ON public.batch_transactions USING btree (lot_id);
CREATE INDEX idx_batch_transactions_operation_type ON public.batch_transactions USING btree (operation_type);
CREATE INDEX idx_batch_transactions_performed_at ON public.batch_transactions USING btree (performed_at DESC);
CREATE INDEX idx_batch_transactions_reference ON public.batch_transactions USING btree (reference_number) WHERE (reference_number IS NOT NULL);
CREATE INDEX idx_batch_transactions_to_warehouse ON public.batch_transactions USING btree (to_warehouse_id);
CREATE INDEX idx_color_supplier_color_id ON public.color_supplier USING btree (color_id);
CREATE INDEX idx_color_supplier_is_active ON public.color_supplier USING btree (is_active) WHERE (is_active = true);
CREATE INDEX idx_color_supplier_supplier_id ON public.color_supplier USING btree (supplier_id);
CREATE INDEX idx_colors_is_active ON public.colors USING btree (is_active) WHERE (is_active = true);
CREATE INDEX idx_colors_name ON public.colors USING btree (name);
CREATE INDEX idx_employee_permissions_employee ON public.employee_permissions USING btree (employee_id);
CREATE INDEX idx_employee_permissions_permission ON public.employee_permissions USING btree (permission_id);
CREATE INDEX idx_refresh_tokens_employee ON public.employee_refresh_tokens USING btree (employee_id);
CREATE INDEX idx_refresh_tokens_expires ON public.employee_refresh_tokens USING btree (expires_at);
CREATE INDEX idx_employee_roles_employee ON public.employee_roles USING btree (employee_id);
CREATE INDEX idx_employee_roles_role ON public.employee_roles USING btree (role_id);
CREATE INDEX idx_employees_department ON public.employees USING btree (department);
CREATE INDEX idx_employees_employee_id ON public.employees USING btree (employee_id);
CREATE INDEX idx_employees_is_active ON public.employees USING btree (is_active);
CREATE INDEX idx_employees_refresh_token ON public.employees USING btree (refresh_token);
CREATE INDEX idx_lots_created_at ON public.lots USING btree (created_at DESC);
CREATE INDEX idx_lots_lot_number ON public.lots USING btree (lot_number);
CREATE INDEX idx_lots_status ON public.lots USING btree (status);
CREATE INDEX idx_lots_supplier_id ON public.lots USING btree (supplier_id);
CREATE INDEX idx_lots_thread_type_id ON public.lots USING btree (thread_type_id);
CREATE INDEX idx_lots_warehouse_id ON public.lots USING btree (warehouse_id);
CREATE INDEX idx_permissions_code ON public.permissions USING btree (code);
CREATE INDEX idx_permissions_module ON public.permissions USING btree (module);
CREATE INDEX idx_permissions_route ON public.permissions USING btree (route_path);
CREATE INDEX idx_role_permissions_permission ON public.role_permissions USING btree (permission_id);
CREATE INDEX idx_role_permissions_role ON public.role_permissions USING btree (role_id);
CREATE INDEX idx_suppliers_code ON public.suppliers USING btree (code);
CREATE INDEX idx_suppliers_is_active ON public.suppliers USING btree (is_active) WHERE (is_active = true);
CREATE INDEX idx_suppliers_name ON public.suppliers USING btree (name);
CREATE INDEX idx_allocation_cones_allocation ON public.thread_allocation_cones USING btree (allocation_id);
CREATE INDEX idx_allocation_cones_cone ON public.thread_allocation_cones USING btree (cone_id);
CREATE INDEX idx_allocations_due_date ON public.thread_allocations USING btree (due_date);
CREATE INDEX idx_allocations_order_id ON public.thread_allocations USING btree (order_id);
CREATE INDEX idx_allocations_pending ON public.thread_allocations USING btree (status) WHERE (status = ANY (ARRAY['PENDING'::allocation_status, 'SOFT'::allocation_status]));
CREATE INDEX idx_allocations_priority ON public.thread_allocations USING btree (priority);
CREATE INDEX idx_allocations_priority_score ON public.thread_allocations USING btree (priority_score DESC);
CREATE INDEX idx_allocations_split_from ON public.thread_allocations USING btree (split_from_id) WHERE (split_from_id IS NOT NULL);
CREATE INDEX idx_allocations_status ON public.thread_allocations USING btree (status);
CREATE INDEX idx_allocations_thread_type ON public.thread_allocations USING btree (thread_type_id);
CREATE INDEX idx_audit_action ON public.thread_audit_log USING btree (action);
CREATE INDEX idx_audit_created ON public.thread_audit_log USING btree (created_at DESC);
CREATE INDEX idx_audit_record ON public.thread_audit_log USING btree (table_name, record_id);
CREATE INDEX idx_audit_table ON public.thread_audit_log USING btree (table_name);
CREATE INDEX idx_conflict_allocations_allocation ON public.thread_conflict_allocations USING btree (allocation_id);
CREATE INDEX idx_conflict_allocations_conflict ON public.thread_conflict_allocations USING btree (conflict_id);
CREATE INDEX idx_conflicts_created ON public.thread_conflicts USING btree (created_at DESC);
CREATE INDEX idx_conflicts_pending ON public.thread_conflicts USING btree (status) WHERE ((status)::text = 'PENDING'::text);
CREATE INDEX idx_conflicts_status ON public.thread_conflicts USING btree (status);
CREATE INDEX idx_conflicts_thread_type ON public.thread_conflicts USING btree (thread_type_id);
CREATE INDEX idx_thread_inventory_available ON public.thread_inventory USING btree (status) WHERE (status = 'AVAILABLE'::cone_status);
CREATE INDEX idx_thread_inventory_cone_id ON public.thread_inventory USING btree (cone_id);
CREATE INDEX idx_thread_inventory_expiry ON public.thread_inventory USING btree (expiry_date) WHERE (expiry_date IS NOT NULL);
CREATE INDEX idx_thread_inventory_fefo ON public.thread_inventory USING btree (is_partial DESC, expiry_date, received_date) WHERE (status = 'AVAILABLE'::cone_status);
CREATE INDEX idx_thread_inventory_is_partial ON public.thread_inventory USING btree (is_partial) WHERE (is_partial = true);
CREATE INDEX idx_thread_inventory_lot_id ON public.thread_inventory USING btree (lot_id) WHERE (lot_id IS NOT NULL);
CREATE INDEX idx_thread_inventory_status ON public.thread_inventory USING btree (status);
CREATE INDEX idx_thread_inventory_thread_type ON public.thread_inventory USING btree (thread_type_id);
CREATE INDEX idx_thread_inventory_warehouse ON public.thread_inventory USING btree (warehouse_id);
CREATE INDEX idx_movements_allocation ON public.thread_movements USING btree (allocation_id);
CREATE INDEX idx_movements_cone ON public.thread_movements USING btree (cone_id);
CREATE INDEX idx_movements_created ON public.thread_movements USING btree (created_at DESC);
CREATE INDEX idx_movements_reference ON public.thread_movements USING btree (reference_type, reference_id);
CREATE INDEX idx_movements_type ON public.thread_movements USING btree (movement_type);
CREATE INDEX idx_recovery_cone ON public.thread_recovery USING btree (cone_id);
CREATE INDEX idx_recovery_created ON public.thread_recovery USING btree (created_at DESC);
CREATE INDEX idx_recovery_pending ON public.thread_recovery USING btree (status) WHERE (status = ANY (ARRAY['INITIATED'::recovery_status, 'PENDING_WEIGH'::recovery_status, 'WEIGHED'::recovery_status]));
CREATE INDEX idx_recovery_status ON public.thread_recovery USING btree (status);
CREATE INDEX idx_thread_types_active ON public.thread_types USING btree (is_active) WHERE (is_active = true);
CREATE INDEX idx_thread_types_code ON public.thread_types USING btree (code);
CREATE INDEX idx_thread_types_color ON public.thread_types USING btree (color);
CREATE INDEX idx_thread_types_color_id ON public.thread_types USING btree (color_id);
CREATE INDEX idx_thread_types_color_supplier_id ON public.thread_types USING btree (color_supplier_id);
CREATE INDEX idx_thread_types_material ON public.thread_types USING btree (material);
CREATE INDEX idx_thread_types_supplier ON public.thread_types USING btree (supplier);
CREATE INDEX idx_thread_types_supplier_id ON public.thread_types USING btree (supplier_id);
CREATE INDEX idx_warehouses_active ON public.warehouses USING btree (is_active);
CREATE INDEX idx_warehouses_code ON public.warehouses USING btree (code);
CREATE INDEX idx_warehouses_parent ON public.warehouses USING btree (parent_id);
CREATE INDEX idx_warehouses_sort ON public.warehouses USING btree (parent_id, sort_order);
CREATE INDEX idx_warehouses_type ON public.warehouses USING btree (type);
