import type { LoginCredentials, ChangePasswordData } from '@/types/auth';
export declare function useAuth(): {
    employee: any;
    isAuthenticated: any;
    isLoading: any;
    permissions: any;
    error: any;
    isRoot: any;
    tempPassword: any;
    init: () => Promise<void>;
    signIn: (credentials: LoginCredentials) => Promise<boolean>;
    signOut: () => Promise<void>;
    changePassword: (data: ChangePasswordData) => Promise<boolean>;
    refreshPermissions: () => Promise<void>;
    hasPermission: (permission: string) => boolean;
    hasAnyPermission: (perms: string[]) => boolean;
    hasAllPermissions: (perms: string[]) => boolean;
    hasRole: (roleCode: string) => boolean;
    isAdmin: () => boolean;
    checkIsRoot: () => boolean;
};
