/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/announcements': RouteRecordInfo<
      '/announcements',
      '/announcements',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/components': RouteRecordInfo<
      '/components',
      '/components',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/employees': RouteRecordInfo<
      '/employees',
      '/employees',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/forbidden': RouteRecordInfo<
      '/forbidden',
      '/forbidden',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/g/[slug]': RouteRecordInfo<
      '/g/[slug]',
      '/g/:slug',
      { slug: ParamValue<true> },
      { slug: ParamValue<false> },
      | never
    >,
    '/guides/': RouteRecordInfo<
      '/guides/',
      '/guides',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/guides/[slug]': RouteRecordInfo<
      '/guides/[slug]',
      '/guides/:slug',
      { slug: ParamValue<true> },
      { slug: ParamValue<false> },
      | never
    >,
    '/guides/editor': RouteRecordInfo<
      '/guides/editor',
      '/guides/editor',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ke-hoach': RouteRecordInfo<
      '/ke-hoach',
      '/ke-hoach',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/kho': RouteRecordInfo<
      '/kho',
      '/kho',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ky-thuat': RouteRecordInfo<
      '/ky-thuat',
      '/ky-thuat',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/nhan-su': RouteRecordInfo<
      '/nhan-su',
      '/nhan-su',
      Record<never, never>,
      Record<never, never>,
      | '/nhan-su/danh-sach'
    >,
    '/nhan-su/danh-sach': RouteRecordInfo<
      '/nhan-su/danh-sach',
      '/nhan-su/danh-sach',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/notification-channels': RouteRecordInfo<
      '/notification-channels',
      '/notification-channels',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/phan-quyen': RouteRecordInfo<
      '/phan-quyen',
      '/phan-quyen',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/qr-demo': RouteRecordInfo<
      '/qr-demo',
      '/qr-demo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/reports/allocations': RouteRecordInfo<
      '/reports/allocations',
      '/reports/allocations',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings': RouteRecordInfo<
      '/settings',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/thread/': RouteRecordInfo<
      '/thread/',
      '/thread',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/thread/allocations': RouteRecordInfo<
      '/thread/allocations',
      '/thread/allocations',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/thread/batch/history': RouteRecordInfo<
      '/thread/batch/history',
      '/thread/batch/history',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/thread/batch/issue': RouteRecordInfo<
      '/thread/batch/issue',
      '/thread/batch/issue',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/thread/batch/receive': RouteRecordInfo<
      '/thread/batch/receive',
      '/thread/batch/receive',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/thread/batch/transfer': RouteRecordInfo<
      '/thread/batch/transfer',
      '/thread/batch/transfer',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/thread/calculation/': RouteRecordInfo<
      '/thread/calculation/',
      '/thread/calculation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/thread/colors': RouteRecordInfo<
      '/thread/colors',
      '/thread/colors',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/thread/dashboard': RouteRecordInfo<
      '/thread/dashboard',
      '/thread/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/thread/inventory': RouteRecordInfo<
      '/thread/inventory',
      '/thread/inventory',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/thread/issues/reconciliation': RouteRecordInfo<
      '/thread/issues/reconciliation',
      '/thread/issues/reconciliation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/thread/issues/v2/': RouteRecordInfo<
      '/thread/issues/v2/',
      '/thread/issues/v2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/thread/issues/v2/[id]': RouteRecordInfo<
      '/thread/issues/v2/[id]',
      '/thread/issues/v2/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/thread/loans': RouteRecordInfo<
      '/thread/loans',
      '/thread/loans',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/thread/lots/': RouteRecordInfo<
      '/thread/lots/',
      '/thread/lots',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/thread/lots/[id]': RouteRecordInfo<
      '/thread/lots/[id]',
      '/thread/lots/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/thread/mobile/issue': RouteRecordInfo<
      '/thread/mobile/issue',
      '/thread/mobile/issue',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/thread/mobile/receive': RouteRecordInfo<
      '/thread/mobile/receive',
      '/thread/mobile/receive',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/thread/mobile/recovery': RouteRecordInfo<
      '/thread/mobile/recovery',
      '/thread/mobile/recovery',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/thread/over-quota-analysis': RouteRecordInfo<
      '/thread/over-quota-analysis',
      '/thread/over-quota-analysis',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/thread/purchase-orders/': RouteRecordInfo<
      '/thread/purchase-orders/',
      '/thread/purchase-orders',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/thread/purchase-orders/[id]': RouteRecordInfo<
      '/thread/purchase-orders/[id]',
      '/thread/purchase-orders/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/thread/purchase-orders/import': RouteRecordInfo<
      '/thread/purchase-orders/import',
      '/thread/purchase-orders/import',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/thread/recovery': RouteRecordInfo<
      '/thread/recovery',
      '/thread/recovery',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/thread/requests': RouteRecordInfo<
      '/thread/requests',
      '/thread/requests',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/thread/return/': RouteRecordInfo<
      '/thread/return/',
      '/thread/return',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/thread/return/[id]': RouteRecordInfo<
      '/thread/return/[id]',
      '/thread/return/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/thread/stocktake': RouteRecordInfo<
      '/thread/stocktake',
      '/thread/stocktake',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/thread/styles/': RouteRecordInfo<
      '/thread/styles/',
      '/thread/styles',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/thread/styles/[id]': RouteRecordInfo<
      '/thread/styles/[id]',
      '/thread/styles/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/thread/styles/with-specs': RouteRecordInfo<
      '/thread/styles/with-specs',
      '/thread/styles/with-specs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/thread/sub-arts/': RouteRecordInfo<
      '/thread/sub-arts/',
      '/thread/sub-arts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/thread/suppliers': RouteRecordInfo<
      '/thread/suppliers',
      '/thread/suppliers',
      Record<never, never>,
      Record<never, never>,
      | '/thread/suppliers/import-colors'
      | '/thread/suppliers/import-tex'
    >,
    '/thread/suppliers/import-colors': RouteRecordInfo<
      '/thread/suppliers/import-colors',
      '/thread/suppliers/import-colors',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/thread/suppliers/import-tex': RouteRecordInfo<
      '/thread/suppliers/import-tex',
      '/thread/suppliers/import-tex',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/thread/weekly-order/': RouteRecordInfo<
      '/thread/weekly-order/',
      '/thread/weekly-order',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/thread/weekly-order/[id]': RouteRecordInfo<
      '/thread/weekly-order/[id]',
      '/thread/weekly-order/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/thread/weekly-order/deliveries': RouteRecordInfo<
      '/thread/weekly-order/deliveries',
      '/thread/weekly-order/deliveries',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/thread/weekly-order/history': RouteRecordInfo<
      '/thread/weekly-order/history',
      '/thread/weekly-order/history',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/thread/weekly-order/leader-review': RouteRecordInfo<
      '/thread/weekly-order/leader-review',
      '/thread/weekly-order/leader-review',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/announcements.vue': {
      routes:
        | '/announcements'
      views:
        | never
    }
    'src/pages/components.vue': {
      routes:
        | '/components'
      views:
        | never
    }
    'src/pages/employees.vue': {
      routes:
        | '/employees'
      views:
        | never
    }
    'src/pages/forbidden.vue': {
      routes:
        | '/forbidden'
      views:
        | never
    }
    'src/pages/g/[slug].vue': {
      routes:
        | '/g/[slug]'
      views:
        | never
    }
    'src/pages/guides/index.vue': {
      routes:
        | '/guides/'
      views:
        | never
    }
    'src/pages/guides/[slug].vue': {
      routes:
        | '/guides/[slug]'
      views:
        | never
    }
    'src/pages/guides/editor.vue': {
      routes:
        | '/guides/editor'
      views:
        | never
    }
    'src/pages/ke-hoach.vue': {
      routes:
        | '/ke-hoach'
      views:
        | never
    }
    'src/pages/kho.vue': {
      routes:
        | '/kho'
      views:
        | never
    }
    'src/pages/ky-thuat.vue': {
      routes:
        | '/ky-thuat'
      views:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
    }
    'src/pages/nhan-su.vue': {
      routes:
        | '/nhan-su'
        | '/nhan-su/danh-sach'
      views:
        | 'default'
    }
    'src/pages/nhan-su/danh-sach.vue': {
      routes:
        | '/nhan-su/danh-sach'
      views:
        | never
    }
    'src/pages/notification-channels.vue': {
      routes:
        | '/notification-channels'
      views:
        | never
    }
    'src/pages/phan-quyen.vue': {
      routes:
        | '/phan-quyen'
      views:
        | never
    }
    'src/pages/qr-demo.vue': {
      routes:
        | '/qr-demo'
      views:
        | never
    }
    'src/pages/reports/allocations.vue': {
      routes:
        | '/reports/allocations'
      views:
        | never
    }
    'src/pages/settings.vue': {
      routes:
        | '/settings'
      views:
        | never
    }
    'src/pages/thread/index.vue': {
      routes:
        | '/thread/'
      views:
        | never
    }
    'src/pages/thread/allocations.vue': {
      routes:
        | '/thread/allocations'
      views:
        | never
    }
    'src/pages/thread/batch/history.vue': {
      routes:
        | '/thread/batch/history'
      views:
        | never
    }
    'src/pages/thread/batch/issue.vue': {
      routes:
        | '/thread/batch/issue'
      views:
        | never
    }
    'src/pages/thread/batch/receive.vue': {
      routes:
        | '/thread/batch/receive'
      views:
        | never
    }
    'src/pages/thread/batch/transfer.vue': {
      routes:
        | '/thread/batch/transfer'
      views:
        | never
    }
    'src/pages/thread/calculation/index.vue': {
      routes:
        | '/thread/calculation/'
      views:
        | never
    }
    'src/pages/thread/colors.vue': {
      routes:
        | '/thread/colors'
      views:
        | never
    }
    'src/pages/thread/dashboard.vue': {
      routes:
        | '/thread/dashboard'
      views:
        | never
    }
    'src/pages/thread/inventory.vue': {
      routes:
        | '/thread/inventory'
      views:
        | never
    }
    'src/pages/thread/issues/reconciliation.vue': {
      routes:
        | '/thread/issues/reconciliation'
      views:
        | never
    }
    'src/pages/thread/issues/v2/index.vue': {
      routes:
        | '/thread/issues/v2/'
      views:
        | never
    }
    'src/pages/thread/issues/v2/[id].vue': {
      routes:
        | '/thread/issues/v2/[id]'
      views:
        | never
    }
    'src/pages/thread/loans.vue': {
      routes:
        | '/thread/loans'
      views:
        | never
    }
    'src/pages/thread/lots/index.vue': {
      routes:
        | '/thread/lots/'
      views:
        | never
    }
    'src/pages/thread/lots/[id].vue': {
      routes:
        | '/thread/lots/[id]'
      views:
        | never
    }
    'src/pages/thread/mobile/issue.vue': {
      routes:
        | '/thread/mobile/issue'
      views:
        | never
    }
    'src/pages/thread/mobile/receive.vue': {
      routes:
        | '/thread/mobile/receive'
      views:
        | never
    }
    'src/pages/thread/mobile/recovery.vue': {
      routes:
        | '/thread/mobile/recovery'
      views:
        | never
    }
    'src/pages/thread/over-quota-analysis.vue': {
      routes:
        | '/thread/over-quota-analysis'
      views:
        | never
    }
    'src/pages/thread/purchase-orders/index.vue': {
      routes:
        | '/thread/purchase-orders/'
      views:
        | never
    }
    'src/pages/thread/purchase-orders/[id].vue': {
      routes:
        | '/thread/purchase-orders/[id]'
      views:
        | never
    }
    'src/pages/thread/purchase-orders/import.vue': {
      routes:
        | '/thread/purchase-orders/import'
      views:
        | never
    }
    'src/pages/thread/recovery.vue': {
      routes:
        | '/thread/recovery'
      views:
        | never
    }
    'src/pages/thread/requests.vue': {
      routes:
        | '/thread/requests'
      views:
        | never
    }
    'src/pages/thread/return/index.vue': {
      routes:
        | '/thread/return/'
      views:
        | never
    }
    'src/pages/thread/return/[id].vue': {
      routes:
        | '/thread/return/[id]'
      views:
        | never
    }
    'src/pages/thread/stocktake.vue': {
      routes:
        | '/thread/stocktake'
      views:
        | never
    }
    'src/pages/thread/styles/index.vue': {
      routes:
        | '/thread/styles/'
      views:
        | never
    }
    'src/pages/thread/styles/[id].vue': {
      routes:
        | '/thread/styles/[id]'
      views:
        | never
    }
    'src/pages/thread/styles/with-specs.vue': {
      routes:
        | '/thread/styles/with-specs'
      views:
        | never
    }
    'src/pages/thread/sub-arts/index.vue': {
      routes:
        | '/thread/sub-arts/'
      views:
        | never
    }
    'src/pages/thread/suppliers.vue': {
      routes:
        | '/thread/suppliers'
        | '/thread/suppliers/import-colors'
        | '/thread/suppliers/import-tex'
      views:
        | 'default'
    }
    'src/pages/thread/suppliers/import-colors.vue': {
      routes:
        | '/thread/suppliers/import-colors'
      views:
        | never
    }
    'src/pages/thread/suppliers/import-tex.vue': {
      routes:
        | '/thread/suppliers/import-tex'
      views:
        | never
    }
    'src/pages/thread/weekly-order/index.vue': {
      routes:
        | '/thread/weekly-order/'
      views:
        | never
    }
    'src/pages/thread/weekly-order/[id].vue': {
      routes:
        | '/thread/weekly-order/[id]'
      views:
        | never
    }
    'src/pages/thread/weekly-order/deliveries.vue': {
      routes:
        | '/thread/weekly-order/deliveries'
      views:
        | never
    }
    'src/pages/thread/weekly-order/history.vue': {
      routes:
        | '/thread/weekly-order/history'
      views:
        | never
    }
    'src/pages/thread/weekly-order/leader-review.vue': {
      routes:
        | '/thread/weekly-order/leader-review'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
