/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/components': RouteRecordInfo<'/components', '/components', Record<never, never>, Record<never, never>>,
    '/employees': RouteRecordInfo<'/employees', '/employees', Record<never, never>, Record<never, never>>,
    '/ke-hoach': RouteRecordInfo<'/ke-hoach', '/ke-hoach', Record<never, never>, Record<never, never>>,
    '/kho': RouteRecordInfo<'/kho', '/kho', Record<never, never>, Record<never, never>>,
    '/ky-thuat': RouteRecordInfo<'/ky-thuat', '/ky-thuat', Record<never, never>, Record<never, never>>,
    '/nhan-su': RouteRecordInfo<'/nhan-su', '/nhan-su', Record<never, never>, Record<never, never>, '/nhan-su/danh-sach'>,
    '/nhan-su/danh-sach': RouteRecordInfo<'/nhan-su/danh-sach', '/nhan-su/danh-sach', Record<never, never>, Record<never, never>>,
    '/phan-quyen': RouteRecordInfo<'/phan-quyen', '/phan-quyen', Record<never, never>, Record<never, never>>,
    '/qr-demo': RouteRecordInfo<'/qr-demo', '/qr-demo', Record<never, never>, Record<never, never>>,
    '/reports/allocations': RouteRecordInfo<'/reports/allocations', '/reports/allocations', Record<never, never>, Record<never, never>>,
    '/thread/': RouteRecordInfo<'/thread/', '/thread', Record<never, never>, Record<never, never>>,
    '/thread/allocations': RouteRecordInfo<'/thread/allocations', '/thread/allocations', Record<never, never>, Record<never, never>>,
    '/thread/batch/history': RouteRecordInfo<'/thread/batch/history', '/thread/batch/history', Record<never, never>, Record<never, never>>,
    '/thread/batch/issue': RouteRecordInfo<'/thread/batch/issue', '/thread/batch/issue', Record<never, never>, Record<never, never>>,
    '/thread/batch/receive': RouteRecordInfo<'/thread/batch/receive', '/thread/batch/receive', Record<never, never>, Record<never, never>>,
    '/thread/batch/transfer': RouteRecordInfo<'/thread/batch/transfer', '/thread/batch/transfer', Record<never, never>, Record<never, never>>,
    '/thread/dashboard': RouteRecordInfo<'/thread/dashboard', '/thread/dashboard', Record<never, never>, Record<never, never>>,
    '/thread/inventory': RouteRecordInfo<'/thread/inventory', '/thread/inventory', Record<never, never>, Record<never, never>>,
    '/thread/lots/': RouteRecordInfo<'/thread/lots/', '/thread/lots', Record<never, never>, Record<never, never>>,
    '/thread/lots/[id]': RouteRecordInfo<'/thread/lots/[id]', '/thread/lots/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/thread/mobile/issue': RouteRecordInfo<'/thread/mobile/issue', '/thread/mobile/issue', Record<never, never>, Record<never, never>>,
    '/thread/mobile/receive': RouteRecordInfo<'/thread/mobile/receive', '/thread/mobile/receive', Record<never, never>, Record<never, never>>,
    '/thread/mobile/recovery': RouteRecordInfo<'/thread/mobile/recovery', '/thread/mobile/recovery', Record<never, never>, Record<never, never>>,
    '/thread/recovery': RouteRecordInfo<'/thread/recovery', '/thread/recovery', Record<never, never>, Record<never, never>>,
    '/thread/requests': RouteRecordInfo<'/thread/requests', '/thread/requests', Record<never, never>, Record<never, never>>,
    '/thread/stocktake': RouteRecordInfo<'/thread/stocktake', '/thread/stocktake', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/components.vue': {
      routes: '/components'
      views: never
    }
    'src/pages/employees.vue': {
      routes: '/employees'
      views: never
    }
    'src/pages/ke-hoach.vue': {
      routes: '/ke-hoach'
      views: never
    }
    'src/pages/kho.vue': {
      routes: '/kho'
      views: never
    }
    'src/pages/ky-thuat.vue': {
      routes: '/ky-thuat'
      views: never
    }
    'src/pages/nhan-su.vue': {
      routes: '/nhan-su' | '/nhan-su/danh-sach'
      views: 'default'
    }
    'src/pages/nhan-su/danh-sach.vue': {
      routes: '/nhan-su/danh-sach'
      views: never
    }
    'src/pages/phan-quyen.vue': {
      routes: '/phan-quyen'
      views: never
    }
    'src/pages/qr-demo.vue': {
      routes: '/qr-demo'
      views: never
    }
    'src/pages/reports/allocations.vue': {
      routes: '/reports/allocations'
      views: never
    }
    'src/pages/thread/index.vue': {
      routes: '/thread/'
      views: never
    }
    'src/pages/thread/allocations.vue': {
      routes: '/thread/allocations'
      views: never
    }
    'src/pages/thread/batch/history.vue': {
      routes: '/thread/batch/history'
      views: never
    }
    'src/pages/thread/batch/issue.vue': {
      routes: '/thread/batch/issue'
      views: never
    }
    'src/pages/thread/batch/receive.vue': {
      routes: '/thread/batch/receive'
      views: never
    }
    'src/pages/thread/batch/transfer.vue': {
      routes: '/thread/batch/transfer'
      views: never
    }
    'src/pages/thread/dashboard.vue': {
      routes: '/thread/dashboard'
      views: never
    }
    'src/pages/thread/inventory.vue': {
      routes: '/thread/inventory'
      views: never
    }
    'src/pages/thread/lots/index.vue': {
      routes: '/thread/lots/'
      views: never
    }
    'src/pages/thread/lots/[id].vue': {
      routes: '/thread/lots/[id]'
      views: never
    }
    'src/pages/thread/mobile/issue.vue': {
      routes: '/thread/mobile/issue'
      views: never
    }
    'src/pages/thread/mobile/receive.vue': {
      routes: '/thread/mobile/receive'
      views: never
    }
    'src/pages/thread/mobile/recovery.vue': {
      routes: '/thread/mobile/recovery'
      views: never
    }
    'src/pages/thread/recovery.vue': {
      routes: '/thread/recovery'
      views: never
    }
    'src/pages/thread/requests.vue': {
      routes: '/thread/requests'
      views: never
    }
    'src/pages/thread/stocktake.vue': {
      routes: '/thread/stocktake'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
