ALTER TABLE thread_inventory ENABLE ROW LEVEL SECURITY;
ALTER TABLE thread_inventory FORCE ROW LEVEL SECURITY;

ALTER TABLE thread_movements ENABLE ROW LEVEL SECURITY;
ALTER TABLE thread_movements FORCE ROW LEVEL SECURITY;

ALTER TABLE thread_allocations ENABLE ROW LEVEL SECURITY;
ALTER TABLE thread_allocations FORCE ROW LEVEL SECURITY;

ALTER TABLE lots ENABLE ROW LEVEL SECURITY;
ALTER TABLE lots FORCE ROW LEVEL SECURITY;

ALTER TABLE purchase_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE purchase_orders FORCE ROW LEVEL SECURITY;

ALTER TABLE thread_order_weeks ENABLE ROW LEVEL SECURITY;
ALTER TABLE thread_order_weeks FORCE ROW LEVEL SECURITY;
